version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pensenbuch-postgres-db:/var/lib/postgresql/data
    ports:
      - 54320:54320
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 15432:80
    volumes:
        - pensenbuch-pgadmin:/var/lib/pgadmin
    depends_on:
        - postgres
volumes:
  pensenbuch-postgres-db:
    external: true
  pensenbuch-pgadmin:
    external: true


